#!/usr/bin/env bash
#script to configure a domain zone so that subdomain points to the lb-01


if [ $# -eq 1 ]; then
	dom="www.$1 lb-01.$1 web-01.$1 web-02.$1"
else
	dom="$2.$1"
fi

dig $dom | awk '/ANSWER SECTION:/{
	getline;
	split($1, b, ".");
	printf "The subdomain %s is a %s record and points to %s\n", b[1], $4, $5
}'
