#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine 
echo -e "Updating and installing Nginx"
apt-get update
apt-get install -y nginx

sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" > /var/www/html/index.html
server_config = "/etc/nginx/sites-available/default"

cat <<EOF> "$server_config"

server {
	listen 80;
	listen [::]:80;

	server_name _;

	location / {
		root /var/www/html;
		index index.html;
	}
}
EOF

kill -s HUP $(pidof nginx)

echo "Nginx installed and configured successfully!"
