#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update && sudo apt-get install nginx

# Start nginx service
sudo service nginx start

# Create index.html with "Hello World!"
sudo touch /var/www/html/index.html
sudo chmod 666 /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

# Create custom 404 error page
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Update Nginx configuration

printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;

	root /etc/nginx/html;
	index index.html index.htm;

	location /redirect_me {
	return 301 http://www.youtube.com/;
	}

	error_page 404 /404.html;
	location /404 {
		root /etc/nginx/html;
		internal;
	}

}" > /etc/nginx/sites-available/default


# Test Nginx configuration for syntax errors
sudo nginx -t

# Restart Nginx to apply changes
service nginx restart
