#!/usr/bin/env bash
# Backup original hosts file
# Update /etc/hosts file to configure hostname resolutions
# Restarting networking service to apply changes

sudo cp /etc/hosts /etc/hosts.backup
sudo sed -i 's/127\.0\.0\.1\slocalhost/127.0.0.2 localhost/' /etc/hosts
sudo sed -i 's/157\.240\.11\.35\sfacebook\.com/8.8.8.8 facebook.com/' /etc/hosts
sudo systemctl restart networking
echo "Hosts file updated successfully!"
