#!/bin/bash

# Update /etc/hosts file to configure hostname resolutions
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

# Restarting networking service to apply changes
sudo systemctl restart networking

# Check if Docker is installed
if ! [ -x "$(command -v docker)" ]; then
  echo 'Error: Docker is not installed. Please install Docker first.' >&2
  exit 1
fi

# Run Docker container for checker
sudo docker run --rm checker-image

