#!/usr/bin/env bash
#Using what you did for task #1, make your fix short and sweet.

sudo sed -i 's/user www-data/user nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo service apache2 stop
sudo -u nginx service nginx start
